# Feature Processing

In [1]:
# Import libraries
import numpy as np
import pandas as pd 
import os 
import sys 

# System configuration
sys.path.append(os.path.join(".."))

## Data Loading

In [3]:
# Import functionalities
from scripts.collection.ingestor import FileIngestor

In [19]:
# Instantiate ingestor object to load required data
selected_folder = r"processed\v1"
file_ingestor = FileIngestor(selected_folder)

# Load the datasets
hardware_data = file_ingestor.ingest(filename="hardware_table.csv")
visual_data = file_ingestor.ingest(filename="visual_table.csv")
processor_data = file_ingestor.ingest(filename="processor_table.csv")
memory_data = file_ingestor.ingest(filename="memory_table.csv")

file_ingestor2 = FileIngestor(folder="external")
dataset = file_ingestor2.ingest(filename="Laptop_numerical_data.csv")

In [9]:
visual_data

,SCREEN_ID,SCREEN_SIZE_INCH,COLOR,WIDTH_DISPLAY,HEIGHT_DISPLAY,DISPLAY,WEBCAM(BUILT-IN)
0,S0,14.00,gray,2160.0,1440.0,NO,YES
1,S1,14.00,black,1920.0,1080.0,YES,YES
2,S2,11.60,black,1366.0,768.0,YES,YES
3,S3,12.50,other,1366.0,768.0,YES,YES
4,S4,11.60,black,1366.0,768.0,NO,YES
...,...,...,...,...,...,...,...
4178,S4178,8.43,other,1920.0,1080.0,NO,NO
4179,S4179,12.50,black,1920.0,1080.0,NO,NO
4180,S4180,8.43,other,1920.0,1080.0,NO,YES
4181,S4181,8.43,black,1920.0,1080.0,NO,NO
4182,NaN,NaN,NaN,NaN,NaN,NO,NO

In [14]:
processor_data

,PROCESSOR_ID,PROCESSOR,PROCESSOR_SPEED,PROCESSOR_SPEED_UNIT
0,P0,quad core,3.8,GHz
1,P1,intel core i5-6300u,2.4,GHz
2,P2,intel celeron n,2.4,GHz
3,P3,intel core i5 6th generation,1.4,GHz
4,P4,intel celeron,1.6,GHz
...,...,...,...,...
4177,P4177,undefined,0.0,unknown
4178,P4178,not applicable,0.0,unknown
4179,P4179,intel core i5 6th generation,2.8,GHz
4180,P4180,not applicable,0.0,unknown
4181,P4181,undefined,0.0,unknown

In [15]:
memory_data

,MEMORY_ID,HARD_DRIVE,HARD_DRIVE_CAPACITY_UNIT,SSD_CAPACITY,SSD_CAPACITY_UNIT
0,M0,512,gb,1,tb
1,M1,500,gb,500,gb
2,M2,16,gb,240,unknown
3,M3,256,unknown,256,gb
4,M4,256,unknown,16,gb
...,...,...,...,...,...
4177,M4177,256,unknown,240,unknown
4178,M4178,256,unknown,240,unknown
4179,M4179,256,unknown,120,gb
4180,M4180,256,unknown,240,unknown
4181,M4181,256,unknown,240,unknown

In [20]:
dataset

,Price,Width of the Display,Height of the Display,Hard Drive Capacity,SSD Capacity,Ram Size,Processor Speed
0,303.80,2160.0,1440.0,512.0,1.0,8.0,3.8
1,400.00,1920.0,1080.0,2.0,NaN,NaN,4.2
2,175.00,1920.0,1080.0,500.0,500.0,16.0,2.4
3,85.00,1366.0,768.0,16.0,NaN,4.0,2.4
4,101.25,1366.0,768.0,NaN,256.0,8.0,1.4
...,...,...,...,...,...,...,...
4178,162.20,NaN,NaN,NaN,NaN,NaN,NaN
4179,93.25,NaN,NaN,NaN,NaN,NaN,NaN
4180,424.80,1920.0,1080.0,NaN,120.0,NaN,2.8
4181,90.94,NaN,NaN,NaN,NaN,NaN,NaN
4182,567.50,NaN,NaN,NaN,NaN,NaN,NaN

## Approach

- Data Transformation
- Data Processing

## Data Transformation

In [29]:
# Extract ram from dataset
ram_feature_df = dataset[["Ram Size"]]
ram_feature_df.loc[:, "Ram Size"] = ram_feature_df["Ram Size"].fillna(0.0)
ram_feature_df.loc[:, "Ram Size"] = ram_feature_df["Ram Size"].replace(0.0, round(ram_feature_df["Ram Size"].mean(), 2))
ram_feature_df.loc[:, "Ram Size"] = ram_feature_df["Ram Size"].apply(lambda x: round(x, 2))
ram_feature_df

      Ram Size
0         8.00
1         8.09
2        16.00
3         4.00
4         8.00
...        ...
4178      8.09
4179      8.09
4180      8.09
4181      8.09
4182      8.09

[4183 rows x 1 columns]

In [ ]:
# a